version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - python -m pytest --cov=dogonabear/ --cov-fail-under 100 tests/
      - aws cloudformation validate-template --template-body file://template.yml
  
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml
